account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import SettingsView
from . import views

app_name = 'account'

urlpatterns = [
    path('auth/login/', auth_views.LoginView.as_view(), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('auth/signup/', views.main, name='signup'),

    path('auth/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('auth/password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('auth/password_reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('settings/', SettingsView.as_view(), name="settings_view"),
]

chat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home import views as home
from new_chat import views as new_chat
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(
        url=staticfiles_storage.url("media/favicon.jpg"))),
    path('', include('home.urls', namespace="home")),
    path('~/', include('client.urls', namespace='client')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('account/', include('account.urls', namespace="account")),
    path('newchat', new_chat.ChatCreateView.as_view(), name="new_chat"),
    path('apps/', include('management.urls', namespace="management")),

    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('rosetta/', include('rosetta.urls')),
    path("store/", include('store.urls', namespace="store")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from .views import DocumentView, StartView

app_name = "docs"

urlpatterns = [
	path('', StartView.as_view(), name="start"),
	path('<path:raw_url>', DocumentView.as_view(), name="document"),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home
from new_chat import views as new_chat
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

app_name = 'home'

urlpatterns = [
    path("", home.Main.as_view(), name="main"),
]

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView

# Create your views here.
class Main(TemplateView):
	template_name = "home/index.html"

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}bla bla{% endblock title %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
        <link rel="stylesheet" href="{% static 'css/nav.css' %}" type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/body.css' %}">
        <script src="{% static 'js/functions.js' %}"></script>
        {% block static %}

        {% endblock static %}
    </head>
	<nav class="nav" id="nav">
		<div class="logo">
			<a href="{% url 'home:main' %}">
				bla bla
			</a>
		</div>
		<div class="links">
			<a href="#">Getting Started</a>
			<a href="{% url 'docs:start' %}">Documentation</a>
			<div class="products-dropdown">
				<a href="javascript: void(0);">Products</a>
				<div class="products-dropdown-content">
					<a href="#">Chat</a>
				</div>
			</div>
			<a href="#">Pricing</a>
<!-- 			<a href="#">Our Mission</a> -->
		</div>
		<div class="auth">
        	<a href="{% url 'account:login' %}">Log In</a>
			<a href="{% url 'account:signup' %}">Sign Up</a>
		</div>
		<hr class="nav-separator">
    </nav>
    <body>

		{% if request.user.is_authenticated and request.resolver_match.app_name == 'home' %}
			<script>
				location.replace("{% url 'client:home' %}");
			</script>
		{% endif %}
        <noscript>
            <div>
                You need to enable javascript to use this page. Please enable it for this site in your browser settings.
            </div>
        </noscript>
        <p style="top: 0; margin-top: 0; opacity: 0;">Some random text that will not show up on the page, but is here to keep the body element at the top of the page</p>
        <div class="beginningAnimationContainer" id="beginningAnimationContainer" hidden>
            <div class="beginningAnimation">
                <span id="logo_text">bla bla</span>
            </div>
        </div>

        {% block sideContent %}

        {% endblock sideContent %}

        <div class="body">
            {% block content %}
                
            {% endblock content %}
        </div>
        <p style="bottom: 0; margin-bottom: 0; opacity: 0;">Some random text that will not show up on the page, but is here to keep the body at the top of the page</p>
        {% block scripts %}
            
        {% endblock scripts %}
    </body>
</html>