chat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home import views as home
from new_chat import views as new_chat
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(
        url=staticfiles_storage.url("media/favicon.jpg"))),
    path('', include('home.urls', namespace="home")),
    path('~/', include('client.urls', namespace='client')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('account/', include('account.urls', namespace="account")),
    path('newchat', new_chat.ChatCreateView.as_view(), name="new_chat"),
    path('apps/', include('management.urls', namespace="management")),

    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('rosetta/', include('rosetta.urls')),
    path("store/", include('store.urls', namespace="store")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path, include
from . import views as client
from .views import (
    AcceptChatView,
    AllChatsListView,
    ChatUserUpdateView,
    ChatView,
    DeleteChatView,
    LeaveChatView,
    PinChatView,
    RecentChatsListView,
    PinnedChatsListView,
    RejectChatView,
    TransferChatView,
    InvitedChatsListView,
)

app_name = "client"

urlpatterns = [
    path('', client.Main.as_view(), name="home"),
    path('chats/<str:name>', ChatView.as_view(), name="detail"),
    path('chats/', AllChatsListView.as_view(), name='allchats'),
    path("chats/recent/", RecentChatsListView.as_view(), name="recent"),
    path('chats/pinned/', PinnedChatsListView.as_view(), name="pinned"),
    path('chats/invited/', InvitedChatsListView.as_view(), name='invited'),
    path('chats/<uuid:location>/settings/',
         ChatUserUpdateView.as_view(), name='update'),
    path('chats/actions/leave/',
         LeaveChatView.as_view(), name='leave'),
    path('chats/actions/delete/',
         DeleteChatView.as_view(), name='delete'),
    path('chats/actions/transfer/',
         TransferChatView.as_view(), name='transfer'),
    path('chats/actions/pin/', PinChatView.as_view(), name='pin'),
    path('chats/actions/accept/', AcceptChatView.as_view(), name='accept'),
    path('chats/actions/reject/', RejectChatView.as_view(), name='reject'),
]

client/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings

import uuid

# Create your models here.


class Chat(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Creator'), on_delete=models.SET_NULL, unique=False, null=True,
                                related_name="creator_of")
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, verbose_name=_('Users'), through='ChatUser', unique=False, related_name="chatUser_of", blank=True)
    description = models.CharField(_('Description'), max_length=100)
    created = models.DateField(
        _('Chat Date Created'), auto_now_add=True)
    location = models.UUIDField(_('Location'), default=uuid.uuid4)
    token = models.UUIDField(_('token'), null=False, editable=False,
                             unique=True, default=uuid.uuid4)

    def get_absolute_url(self):
        return reverse_lazy("client:detail", args=[self.location])

    class Meta:
        verbose_name = _('Chat')
        verbose_name_plural = _('Chats')


class ChatSettings(models.Model):
    """Model definition for ChatSettings."""

    chat = models.OneToOneField('Chat', verbose_name=_(
        'Chat'), on_delete=models.CASCADE, related_name="settings", db_index=True)

    class Meta:
        """Meta definition for Settings."""

        verbose_name = _('Chat Settings')
        verbose_name_plural = _('Chat Settings')

    def __str__(self):
        """Unicode representation of Chat Settings."""
        return self.chat.description + ' settings'


class ChatUser(models.Model):
    """Intermediary model for Chat ManyToManyField."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        'User'), on_delete=models.CASCADE)
    chat = models.ForeignKey('Chat', verbose_name=_(
        'Chat'), on_delete=models.CASCADE)
    accepted = models.BooleanField(_('Accepted'), default=False)
    pinned = models.BooleanField(_('Pinned'), default=False)

    class Meta:
        """Meta definition for ChatUser."""

        verbose_name = _('ChatUser')
        verbose_name_plural = _('ChatUsers')

    def __str__(self):
        """Unicode representation of ChatUser."""
        if self.accepted:
            return self.user.username + ' is a member of ' + self.chat.description
        else:
            return self.user.username + ' is invited to ' + self.chat.description


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name=_(
        'Chat'), on_delete=models.CASCADE, db_column="chat", related_name="messages")
    message = models.TextField(_('Message'))
    creator = models.TextField(_('Creator'))
    date = models.DateTimeField(_('Date'))

    class Meta:
        """Meta definition for Message."""

        verbose_name = _('Message')
        verbose_name_plural = _('Messages')

client/forms.py
from django import forms
from django.contrib.auth.models import User

class UserEditForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

client/views.py
from curses import raw
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import ListView, UpdateView, View

from client.extensions import *

from .models import Chat
from .models import ChatUser

# Create your views here.


class Main(LoginRequiredMixin, ListView):
    model = Chat
    template_name = "client/index.html"


class ChatListMixin(LoginRequiredMixin, ListView):
    model = Chat
    template_name_suffix = "_list"

    def get_queryset(self):
        self.user_of_list = []

        queryset = super().get_queryset()

        self.creator_of = queryset.filter(
            creator=self.request.user).order_by('-created')

        users = ChatUser.objects.filter(
            user=self.request.user, accepted=True).all()

        for user in users:
            self.user_of_list.append(user.chat.id)

        self.user_of = Chat.objects.filter(id__in=self.user_of_list).all()

        return self.user_of


class AllChatsListView(ChatListMixin):
    pass


class RecentChatsListView(ChatListMixin):
    def get_queryset(self):
        queryset = super().get_queryset()

        if queryset.count() > 10:
            queryset = queryset[:7]

        return queryset


class PinnedChatsListView(ChatListMixin):
    template_name_suffix = '_list_pinned'

    def get_queryset(self):
        super().get_queryset()
        chats = ChatUser.objects.filter(pinned=True).values_list('chat')
        queryset = self.user_of.filter(id__in=chats)
        return queryset


class InvitedChatsListView(ListView, LoginRequiredMixin):
    template_name_suffix = '_list_invited'
    model = Chat

    def get_queryset(self):
        queryset = super().get_queryset()
        chats = ChatUser.objects.filter(
            accepted=False, user=self.request.user).values_list('chat')
        queryset = queryset.filter(id__in=chats)
        return queryset


class ChatUserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ChatUser
    template_name = "client/chat_update.html"
    fields = ['pinned']
    success_url = reverse_lazy('client:allchats')
    success_message = _("The chat was successfully updated.")

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_object(self, queryset=None):
        queryset = self.get_queryset() if queryset is None else queryset
        chat = get_object_or_404(Chat, location=self.kwargs['location'])
        settings = get_object_or_404(queryset, chat=chat)
        return settings


class ChatView(LoginRequiredMixin, View):
    def get(self, request, name, *args, **kwargs):
        try:
            chat = Chat.objects.get(location=name)
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")

        data = {
            'chat_name': chat.description[:50] + '...',
            'chat_token': chat.token,
            'chatMessages': chat.messages.all(),
        }

        return render(request, 'client/client.html', data)


class LeaveChatView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            chat = Chat.objects.get(location=request.POST.get('location'))
            if not self.request.user == chat.creator:
                chat.users.remove(self.request.user)
                messages.success(request, _("You have left the chat."))
            return redirect('client:allchats')
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")


class DeleteChatView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            chat = Chat.objects.get(location=request.POST.get('location'))
            if self.request.user == chat.creator:
                chat.delete()
                messages.success(request, _("You have deleted the chat."))
            return redirect('client:allchats')
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")


class TransferChatView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            chat = Chat.objects.filter(location=request.POST.get('location'))
            if self.request.user == chat[0].creator:
                # chat.creator = User.objects.get(
                #     username=request.POST.get('users').strip())
                chat.update(creator=User.objects.get(
                    username=request.POST.get('users').strip()))
                # chat.creator = User.objects.get(
                # username=request.POST.get('users').strip())
                messages.success(request, _("Chat transferred successfully."))
            else:
                raise PermissionDenied()
            return redirect(reverse('client:update', args=[request.POST.get('location')]))
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")


class PinChatView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            chat = get_object_or_404(
                Chat, location=request.GET.get('location'))
            chatUser = get_object_or_404(
                ChatUser, chat=chat, user=self.request.user)

            if chatUser.pinned:
                chatUser.pinned = False

            else:
                chatUser.pinned = True

            chatUser.save()
            return JsonResponse({
                "success": True,
            })

        except:
            pass

        return HttpResponseNotFound()


class AcceptChatView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            chat = get_object_or_404(
                Chat, location=request.GET.get('location'))

            chatUser = get_object_or_404(
                ChatUser, chat=chat, user=self.request.user)

            chatUser.accepted = True

            chatUser.save()

            return JsonResponse({
                "success": True,
            })

        except:
            pass

        return HttpResponseNotFound()


class RejectChatView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            chat = get_object_or_404(
                Chat, location=request.GET.get('location'))

            chatUser = get_object_or_404(
                ChatUser, chat=chat, user=self.request.user)

            chatUser.delete()

            return JsonResponse({
                "success": True,
            })

        except:
            pass

        return HttpResponseNotFound()

project/chat/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import chats as all_chats
from .models import chats

# Create your views here.

# @login_required
# def main(request, *args, **krargs):
# 	data = {
# 		'chat_number': all_chats.objects.all(),
# 		'first_name': request.user.first_name,
# 		'last_name': request.user.last_name,
# 		'username': request.user.username,
# 		'chats': all_chats.objects.filter(chat_creator = request.user.username),
# 	}
# 	return render(request, "main/index.html", data)

class main(LoginRequiredMixin, ListView):
	def get(self, request, *args, **krargs):
		print("test")
		data = {
			'chat_number': len(all_chats.objects.filter(chat_creator = request.user.username)),
			'first_name': request.user.first_name,
			'last_name': request.user.last_name,
			'username': request.user.username,
			'chats': all_chats.objects.filter(chat_creator = request.user.username),
		}
		print(all_chats.objects.filter(chat_creator = request.user.username).count())
		return render(request, "main/index.html", data)

class ChatsView(DetailView):
	def get(self, request, *args, **krargs):
		data = {
			"objects": all_chats.objects.filter(chat_creator = request.user.username),
			"chat": krargs
		}
		return render(request, "main/chat.html", data)

client/templates/client/chat-not-found.html
{% extends 'base.html' %}
{% block content %}
    <center><i>Chat not found.</i></center>
{% endblock content %}

client/templates/client/chat_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block extrastyle %}
    <link rel="stylesheet"
          href="{% static 'css/chat-list.css' %}"
          type="text/css">
{% endblock extrastyle %}
{% block content %}
    <div class="chats-detail">
        {% block loop %}
            {% for chat in object_list %}
                {% include 'client/chats.html' with chat=chat %}
            {% empty %}
                <center>
                    <i>
                        {% block empty_queryset %}
                            {% trans "You have no chats. " %}<a href="{% url 'new_chat' %}">{% trans "Create One" %}</a>
                        {% endblock empty_queryset %}
                    </i>
                </center>
            {% endfor %}
        {% endblock loop %}
    </div>
{% endblock content %}
{% block extrascripts %}
    <script src="{% static 'js/chats.js' %}"></script>
    {% block js %}
    {% endblock js %}
{% endblock extrascripts %}

client/templates/client/chat_list_invited.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block extrastyle %}
    <link rel="stylesheet"
          href="{% static 'css/chat-list.css' %}"
          type="text/css">
{% endblock extrastyle %}
{% block content %}
    <div class="chats-detail">
        {% block loop %}
            {% for chat in object_list %}
                <div class="no-pointer chat">
                    <center>
                        <span class="description">{{ chat.description }}</span>
                        <br>
                        <span class="users">
                            <b>
                                {% if chat.creator == request.user %}
                                    {% trans "Me" %}
                                {% else %}
                                    {% with chat.creator as creator %}
                                        {% if creator.first_name == '' %}
                                            {{ creator.username }}
                                        {% else %}
                                            {{ creator.first_name }}
                                        {% endif %}
                                    {% endwith %}
                                {% endif %}
                            </b>
                            {% for user in chat.users.all %}
                                {% if user != chat.creator %}
                                    {% trans "," %}
                                    {{ user.username }}
                                {% endif %}
                            {% endfor %}
                        </span>
                        <br>
                        <span class="created">{{ chat.created }}</span>
                        <br>
                        <br>
                        <hr class="accept-or-reject-separator">
                        <input type="button"
                               value="Accept"
                               class="btn accept"
                               data-chat="{{ chat.location }}"
                               data-url="{% url 'client:accept' %}">
                        <input type="button"
                               value="Reject"
                               class="btn reject"
                               data-chat="{{ chat.location }}"
                               data-url="{% url 'client:reject' %}">
                    </center>
                </div>
            {% empty %}
                <center>
                    <i>
                        {% block empty_queryset %}
                            {% trans "You have not been invited to any chats. " %}
                        {% endblock empty_queryset %}
                    </i>
                </center>
            {% endfor %}
        {% endblock loop %}
    </div>
{% endblock content %}
{% block extrascripts %}
    <script src="{% static 'js/chats.js' %}"></script>
    <script src="{% static 'js/accept-chat.js' %}"></script>
{% endblock extrascripts %}

client/templates/client/chat_list_pinned.html
{% extends 'client/chat_list.html' %}
{% load i18n %}
{% load static %}
{% block empty_queryset %}
    {% trans 'You have no pinned chats.' %}
{% endblock empty_queryset %}
{% block js %}
    <script src="{% static 'js/pinned.js' %}" type="text/javascript"></script>
{% endblock js %}

client/templates/client/chat_update.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block extrastyle %}
    <link rel="stylesheet"
          href="{% static 'css/chat-update.css' %}"
          type="text/css">
{% endblock extrastyle %}
{% block content %}
    <dialog class="delete-dialog" id="delete-dialog">
        <form action="{% url 'client:delete' %}" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete this chat?</p>
            <input type="hidden" name="location" value="{{ form.instance.chat.location }}">
            <input type="submit" value="{% trans 'Yes, delete this chat' %}" class="btn" />
            <input type="button" value="No, go back" class="btn cancel-dialog" />
        </form>
    </dialog>
    <dialog class="leave-dialog" id="leave-dialog">
        <form action="{% url 'client:leave' %}" method="post">
            {% csrf_token %}
            <p>Are you sure you want to leave this chat?</p>
            <input type="hidden" name="location" value="{{ form.instance.chat.location }}">
            <input type="submit" value="{% trans 'Yes, leave this chat' %}" class="btn" />
            <input type="button" value="No, go back" class="btn cancel-dialog" />
        </form>
    </dialog>
    <dialog class="transfer-dialog" id="transfer-dialog">
        <form action="{% url 'client:transfer' %}" method="post">
            {% csrf_token %}
            <input type="hidden"
                   name="location"
                   value="{{ form.instance.chat.location }}">
            <label for="users">Who do you want to transfer this chat to?</label>
            <div class="select-wrapper">
                <div class="selected-user">
                    <span class="user">
                        {% with user.get_full_name|truncatechars:11 as name %}
                            {% if not name %}
                                {{ user.username|truncatechars:11 }}
                            {% else %}
                                {{ name }}
                            {% endif %}
                        {% endwith %}
                    </span>
                    <span class="caret"></span>
                </div>
                <div class="select-options" id="select-options">
                    <hr class="separator" />
                    {% for user in form.instance.chat.users.all %}
                        {% if user != form.instance.chat.creator %}
                            <div class="select-option">
                                {% with user.get_full_name|truncatechars:11 as name %}
                                    {% if not name %}
                                        {{ user.username|truncatechars:11 }}
                                    {% else %}
                                        {{ name }}
                                    {% endif %}
                                {% endwith %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <select name="users" id="users-select">
                    {% for user in form.instance.chat.users.all %}
                        <option value="{{ user.username }}"
                                {% if user == form.instance.chat.creator %} selected{% endif %}>
                            {% with user.get_full_name|truncatechars:18 as name %}
                                {% if not name %}
                                    {{ user.username }}
                                {% else %}
                                    {{ name }}
                                {% endif %}
                            {% endwith %}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Transfer" class="btn">
            <input type="button" value="Cancel" class="btn cancel-dialog cancel-transfer"/>
        </form>
    </dialog>
    <div class="form-wrapper">
        <div class="form">
            <p class="chat-name">
                {% blocktrans with description=form.instance.chat.description %}
                    Settings for {{ description }}
                {% endblocktrans %}
            </p>
            <a class="close"
               href="{% url 'client:allchats' %}"
               id="close_image_wrapper">
                <img src="{% static 'images/close.png' %}"
                     data-src-default="{% static 'images/close.png' %}"
                     data-src-black="{% static 'images/close_black.png' %}"
                     width="30px"
                     height="30px"
                     alt="Close"
                     id="close_img">
            </a>
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                        <label for="{{ field.name }}">{{ field.label }}:</label>
                        <div class="checkbox-wrapper">
                            {{ field }}
                            <div class="checkbox"></div>
                            <img class="checkbox-checked" src="{% static 'images/checkmark.png' %}">
                        </div>
                    {% else %}
                        <label for="{{ field.name }}">{{ field.label }}:</label>
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <br>
                <input type="submit" value="Change" class="btn change-submit-primary">
            </form>
            <div class="danger-wrapper">
                {% with form.instance.chat as chat %}
                    <fieldset class="danger">
                        <legend>
                            {% trans 'Danger Zone' %}
                        </legend>
                        {% if chat.creator == request.user %}
                            <div class="danger-option">
                                <div class="info">
                                    <p class="title">{% trans 'Delete' %}</p>
                                    <p class="description">{% trans 'Your chat will be deleted. This action is irreversible.' %}</p>
                                </div>
                                <a href="javascript:handleDeleteClicked();">{% trans 'Delete' %}</a>
                            </div>
                            <hr>
                            <div class="danger-option">
                                <div class="info">
                                    <p class="title">{% trans 'Transfer Ownership' %}</p>
                                    <p class="description">
                                        {% trans 'You will transfer all administrative privileges of this chat to the selected person. This action is irreversible.' %}
                                    </p>
                                </div>
                                <a href="javascript:handleTransferClicked();">{% trans 'Transfer' %}</a>
                            </div>
                        {% else %}
                            <div class="danger-option">
                                <div class="info">
                                    <p class="title">{% trans 'Leave' %}</p>
                                    <p class="description">{% trans "You will be removed from this chat. You can't rejoin unless you are reinvited." %}</p>
                                </div>
                                <a href="javascript:handleLeaveClicked();">{% trans 'Leave' %}</a>
                            </div>
                        {% endif %}
                    </fieldset>
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock content %}
{% block extrascripts %}
    <script src="{% static 'js/chat-update.js' %}" type="text/javascript"></script>
{% endblock extrascripts %}

client/templates/client/chats.html
{% load static %}
{% load i18n %}
{% load chat_tags %}
<div class="chat pointer"
     data-url="{% url 'client:detail' chat.location %}">
    <span class="description">{{ chat.description }}</span>
    <br>
    <span class="users">
        <b>
            {% if chat.creator == request.user %}
                {% trans "Me" %}
            {% else %}
                {% with chat.creator as creator %}
                    {% if creator.first_name == '' %}
                        {{ creator.username }}
                    {% else %}
                        {{ creator.first_name }}
                    {% endif %}
                {% endwith %}
            {% endif %}
        </b>
        {% for user in chat.users.all %}
            {% get_chatUser_for_chat chat user.id as chatUser %}
            {% if user != chat.creator and chatUser.accepted %}
                {% trans "," %}
                {{ user.username }}
            {% endif %}
        {% endfor %}
    </span>
    <br>
    <span class="created">{{ chat.created }}</span>
    <div class="update">
        <div class="quick-actions no-redirect">
            <div class="quick-action pin-button no-redirect"
                 data-url="{% url 'client:pin' %}"
                 data-chat="{{ chat.location }}">
                {% get_chatUser_for_chat chat as chatUser %}
                {% if chatUser.pinned %}
                    <img class="no-redirect"
                         src="{% static 'images/pin_filled.png' %}"
                         data-pinned="{% static 'images/pin_filled.png' %}"
                         alt="Pin"
                         width="23px"
                         height="23px">
                {% else %}
                    <img class="no-redirect action-img"
                         src="{% static 'images/pin.png' %}"
                         data-pinned="{% static 'images/pin_filled.png' %}"
                         data-pin="{% static 'images/pin.png' %}"
                         alt="Pinned"
                         width="23px"
                         height="23px">
                {% endif %}
            </div>
        </div>
        <a href="{% url 'client:update' chat.location %}" class="settings">
            <img src="{% static 'images/settings-gear.png' %}"
                 alt="gear"
                 height="40px">
            <span><i>{% trans 'Settings' %}</i></span>
        </a>
    </div>
</div>

client/templates/client/chats_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block extrastyle %}
    <link rel="stylesheet"
          href="{% static 'css/chat-list.css' %}"
          type="text/css">
{% endblock extrastyle %}
{% block content %}
    <div class="chats-detail">
        {% block loop %}
            {% for chat in object_list %}
                {% include 'client/chats.html' with chat=chat %}
            {% empty %}
                <center>
                    <i>
                        {% block empty_queryset %}
                            {% trans "You have no chats. " %}<a href="{% url 'new_chat' %}">{% trans "Create One" %}</a>
                        {% endblock empty_queryset %}
                    </i>
                </center>
            {% endfor %}
        {% endblock loop %}
    </div>
{% endblock content %}
{% block extrascripts %}
    <script src="{% static 'js/chat_whitespace.js' %}"></script>
{% endblock extrascripts %}

client/templates/client/chats_list_invited.html
{% extends 'client/chats_list.html' %}
{% load i18n %}
{% block empty_queryset %}
    {% trans 'You have no chats that you haven\'t joined.' %}
{% endblock empty_queryset %}

client/templates/client/chats_list_pinned.html
{% extends 'client/chats_list.html' %}
{% load i18n %}
{% block empty_queryset %}
    {% trans 'You have no pinned chats.' %}
{% endblock empty_queryset %}

client/templates/client/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock content %}