account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import SettingsView
from . import views

app_name = 'account'

urlpatterns = [
    path('auth/login/', auth_views.LoginView.as_view(), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('auth/signup/', views.main, name='signup'),

    path('auth/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('auth/password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('auth/password_reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('settings/', SettingsView.as_view(), name="settings_view"),
]

chat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home import views as home
from new_chat import views as new_chat
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(
        url=staticfiles_storage.url("media/favicon.jpg"))),
    path('', include('home.urls', namespace="home")),
    path('~/', include('client.urls', namespace='client')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('account/', include('account.urls', namespace="account")),
    path('newchat', new_chat.ChatCreateView.as_view(), name="new_chat"),
    path('apps/', include('management.urls', namespace="management")),

    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('rosetta/', include('rosetta.urls')),
    path("store/", include('store.urls', namespace="store")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path, include
from . import views as client
from .views import (
    AcceptChatView,
    AllChatsListView,
    ChatUserUpdateView,
    ChatView,
    DeleteChatView,
    LeaveChatView,
    PinChatView,
    RecentChatsListView,
    PinnedChatsListView,
    RejectChatView,
    TransferChatView,
    InvitedChatsListView,
)

app_name = "client"

urlpatterns = [
    path('', client.Main.as_view(), name="home"),
    path('chats/<str:name>', ChatView.as_view(), name="detail"),
    path('chats/', AllChatsListView.as_view(), name='allchats'),
    path("chats/recent/", RecentChatsListView.as_view(), name="recent"),
    path('chats/pinned/', PinnedChatsListView.as_view(), name="pinned"),
    path('chats/invited/', InvitedChatsListView.as_view(), name='invited'),
    path('chats/<uuid:location>/settings/',
         ChatUserUpdateView.as_view(), name='update'),
    path('chats/actions/leave/',
         LeaveChatView.as_view(), name='leave'),
    path('chats/actions/delete/',
         DeleteChatView.as_view(), name='delete'),
    path('chats/actions/transfer/',
         TransferChatView.as_view(), name='transfer'),
    path('chats/actions/pin/', PinChatView.as_view(), name='pin'),
    path('chats/actions/accept/', AcceptChatView.as_view(), name='accept'),
    path('chats/actions/reject/', RejectChatView.as_view(), name='reject'),
]

management/urls.py
from django.urls import path
from .views import AppListView

app_name = 'management'

urlpatterns = [
    path('', AppListView.as_view(), name='apps'),
]

client/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings

import uuid

# Create your models here.


class Chat(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Creator'), on_delete=models.SET_NULL, unique=False, null=True,
                                related_name="creator_of")
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, verbose_name=_('Users'), through='ChatUser', unique=False, related_name="chatUser_of", blank=True)
    description = models.CharField(_('Description'), max_length=100)
    created = models.DateField(
        _('Chat Date Created'), auto_now_add=True)
    location = models.UUIDField(_('Location'), default=uuid.uuid4)
    token = models.UUIDField(_('token'), null=False, editable=False,
                             unique=True, default=uuid.uuid4)

    def get_absolute_url(self):
        return reverse_lazy("client:detail", args=[self.location])

    class Meta:
        verbose_name = _('Chat')
        verbose_name_plural = _('Chats')


class ChatSettings(models.Model):
    """Model definition for ChatSettings."""

    chat = models.OneToOneField('Chat', verbose_name=_(
        'Chat'), on_delete=models.CASCADE, related_name="settings", db_index=True)

    class Meta:
        """Meta definition for Settings."""

        verbose_name = _('Chat Settings')
        verbose_name_plural = _('Chat Settings')

    def __str__(self):
        """Unicode representation of Chat Settings."""
        return self.chat.description + ' settings'


class ChatUser(models.Model):
    """Intermediary model for Chat ManyToManyField."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        'User'), on_delete=models.CASCADE)
    chat = models.ForeignKey('Chat', verbose_name=_(
        'Chat'), on_delete=models.CASCADE)
    accepted = models.BooleanField(_('Accepted'), default=False)
    pinned = models.BooleanField(_('Pinned'), default=False)

    class Meta:
        """Meta definition for ChatUser."""

        verbose_name = _('ChatUser')
        verbose_name_plural = _('ChatUsers')

    def __str__(self):
        """Unicode representation of ChatUser."""
        if self.accepted:
            return self.user.username + ' is a member of ' + self.chat.description
        else:
            return self.user.username + ' is invited to ' + self.chat.description


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name=_(
        'Chat'), on_delete=models.CASCADE, db_column="chat", related_name="messages")
    message = models.TextField(_('Message'))
    creator = models.TextField(_('Creator'))
    date = models.DateTimeField(_('Date'))

    class Meta:
        """Meta definition for Message."""

        verbose_name = _('Message')
        verbose_name_plural = _('Messages')

client/forms.py
from django import forms
from django.contrib.auth.models import User

class UserEditForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

client/views.py
from curses import raw
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import ListView, UpdateView, View

from client.extensions import *

from .models import Chat
from .models import ChatUser

# Create your views here.


class Main(LoginRequiredMixin, ListView):
    model = Chat
    template_name = "client/index.html"


class ChatListMixin(LoginRequiredMixin, ListView):
    model = Chat
    template_name_suffix = "_list"

    def get_queryset(self):
        self.user_of_list = []

        queryset = super().get_queryset()

        self.creator_of = queryset.filter(
            creator=self.request.user).order_by('-created')

        users = ChatUser.objects.filter(
            user=self.request.user, accepted=True).all()

        for user in users:
            self.user_of_list.append(user.chat.id)

        self.user_of = Chat.objects.filter(id__in=self.user_of_list).all()

        return self.user_of


class AllChatsListView(ChatListMixin):
    pass


class RecentChatsListView(ChatListMixin):
    def get_queryset(self):
        queryset = super().get_queryset()

        if queryset.count() > 10:
            queryset = queryset[:7]

        return queryset


class PinnedChatsListView(ChatListMixin):
    template_name_suffix = '_list_pinned'

    def get_queryset(self):
        super().get_queryset()
        chats = ChatUser.objects.filter(pinned=True).values_list('chat')
        queryset = self.user_of.filter(id__in=chats)
        return queryset


class InvitedChatsListView(ListView, LoginRequiredMixin):
    template_name_suffix = '_list_invited'
    model = Chat

    def get_queryset(self):
        queryset = super().get_queryset()
        chats = ChatUser.objects.filter(
            accepted=False, user=self.request.user).values_list('chat')
        queryset = queryset.filter(id__in=chats)
        return queryset


class ChatUserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ChatUser
    template_name = "client/chat_update.html"
    fields = ['pinned']
    success_url = reverse_lazy('client:allchats')
    success_message = _("The chat was successfully updated.")

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_object(self, queryset=None):
        queryset = self.get_queryset() if queryset is None else queryset
        chat = get_object_or_404(Chat, location=self.kwargs['location'])
        settings = get_object_or_404(queryset, chat=chat)
        return settings


class ChatView(LoginRequiredMixin, View):
    def get(self, request, name, *args, **kwargs):
        try:
            chat = Chat.objects.get(location=name)
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")

        data = {
            'chat_name': chat.description[:50] + '...',
            'chat_token': chat.token,
            'chatMessages': chat.messages.all(),
        }

        return render(request, 'client/client.html', data)


class LeaveChatView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            chat = Chat.objects.get(location=request.POST.get('location'))
            if not self.request.user == chat.creator:
                chat.users.remove(self.request.user)
                messages.success(request, _("You have left the chat."))
            return redirect('client:allchats')
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")


class DeleteChatView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            chat = Chat.objects.get(location=request.POST.get('location'))
            if self.request.user == chat.creator:
                chat.delete()
                messages.success(request, _("You have deleted the chat."))
            return redirect('client:allchats')
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")


class TransferChatView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            chat = Chat.objects.filter(location=request.POST.get('location'))
            if self.request.user == chat[0].creator:
                # chat.creator = User.objects.get(
                #     username=request.POST.get('users').strip())
                chat.update(creator=User.objects.get(
                    username=request.POST.get('users').strip()))
                # chat.creator = User.objects.get(
                # username=request.POST.get('users').strip())
                messages.success(request, _("Chat transferred successfully."))
            else:
                raise PermissionDenied()
            return redirect(reverse('client:update', args=[request.POST.get('location')]))
        except Chat.DoesNotExist:
            return render(request, "client/chat-not-found.html")


class PinChatView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            chat = get_object_or_404(
                Chat, location=request.GET.get('location'))
            chatUser = get_object_or_404(
                ChatUser, chat=chat, user=self.request.user)

            if chatUser.pinned:
                chatUser.pinned = False

            else:
                chatUser.pinned = True

            chatUser.save()
            return JsonResponse({
                "success": True,
            })

        except:
            pass

        return HttpResponseNotFound()


class AcceptChatView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            chat = get_object_or_404(
                Chat, location=request.GET.get('location'))

            chatUser = get_object_or_404(
                ChatUser, chat=chat, user=self.request.user)

            chatUser.accepted = True

            chatUser.save()

            return JsonResponse({
                "success": True,
            })

        except:
            pass

        return HttpResponseNotFound()


class RejectChatView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            chat = get_object_or_404(
                Chat, location=request.GET.get('location'))

            chatUser = get_object_or_404(
                ChatUser, chat=chat, user=self.request.user)

            chatUser.delete()

            return JsonResponse({
                "success": True,
            })

        except:
            pass

        return HttpResponseNotFound()

client/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en-us" dir="ltr">
    <head>
        <title>Chat</title>
        <meta charset="utf-8">
        <meta name="content-type" content="utf-8">
        <meta name="description" content="A chat site"/>
        <meta name="keywords" content="chat, communication"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
        <link rel="stylesheet"
              href="{% static 'css/nav-bar.css' %}"
              type="text/css">
        <link rel="stylesheet"
              href="{% static 'css/chat-grid.css' %}"
              type="text/css">
        <link rel="stylesheet"
              href="{% static 'css/controls.css' %}"
              type="text/css">
        <script src="{% static 'js/jquery/jquery.js' %}" charset="utf-8" type="text/javascript"></script>
        <script src="{% static 'js/base.js' %}" charset="utf-8" type="text/javascript"></script>
        <script src="{% static 'js/searchSocket.js' %}" charset="utf-8" type="text/javascript"></script>
        {% block extrastyle %}
        {% endblock extrastyle %}
        {% block extra_scripts %}
        {% endblock extra_scripts %}
    </head>
    <body>
        <div id="notifacations-container"></div>
        {% comment %} <div class="top-nav">
      <a href="{% url 'client:home' %}" id="dashboardLink">Home</a>
      <div class="profile">
        <div class="title" onclick="replace(`{% url 'account:settings_view' %}`);">
          <p id="settingsUsername">
            {{ username|truncatechars:15 }}
          </p>
        </div>
      </div>
        </div> {% endcomment %}
        <div class="controlsSpace"></div>
        <div class="controls" id="controls">
            <div class="controls-top">
                <span class="time controls-top-item detail-only" id='time'></span>
                <span class="controls-top-right">
                    <span class="detail-only notifications">
                        <img src="{% static 'images/bell.png' %}"
                             alt="Notification Bell"
                             width="20px"
                             height="20px"
                             class="controls-top-item">
                    </span>
                </span>
            </div>
            <div class="apps">
                <a class="sidelink" href="{% url 'client:home' %}">
                    <img src="{% static 'images/home_icon.png' %}"
                         alt="Home Icon"
                         width="30px"
                         height="30px">
                    <span class="sidelink-label">{% trans 'Home' %}</span>
                </a>
                <a class="sidelink" href="{% url 'management:apps' %}">
                    <img src="{% static 'images/apps_icon.png' %}"
                         alt="Apps Icon"
                         width="30px"
                         height="30px">
                    <span class="sidelink-label">{% trans 'Apps' %}</span>
                </a>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <div class="django-message {% if message.tags %}django-message-{{ message.tags }}{% endif %}">
                        <span>{{ message }}</span>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        {% comment %} <span class="apps-link sidelink">Apps</span> {% endcomment %}
        {% comment %} <span class="new-chat-plus sidelink" onclick="location.replace(`{% url 'new_chat' %}`)">+<span> {% endcomment %}
        {% if messages %}
            {% for message in messages %}
                <div class="django-message {% if message.tags %}django-message-{{ message.tags }}{% endif %}">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
        {% comment %} {% block chat_name %}{% endblock %} {% endcomment %}
    </div>
    <div class="chat-grid-container" id="chat-grid-container">
        <div class="chat-grid">
            <div class="chats chat-grid-object" id="chats">
                <div class="filters">
                    <a href="{% url 'client:allchats' %}">{% trans 'All Chats' %}</a>
                    <a href="{% url 'client:invited' %}">{% trans "Invited" %}</a>
                    <a href="{% url 'client:recent' %}">{% trans "Recent" %}</a>
                    <a href="{% url 'client:pinned' %}">{% trans 'Pinned' %}</a>
                </div>
                <a href="{% url 'new_chat' %}" class="chat-create-btn">{% trans 'New' %}</a>
                {% comment %} <input type="text" name="" value="" class="search-input" placeholder="search by description" id="searchInput" autocomplete='off' onkeyup="searchChat()">
                    <hr>
                    {% if chat_number == 0 %}
                        <p>
                            <i><center>You don't have any chats yet.</center></i>
                        </p>
                    {% endif %}
                    <div id="chat-messages">
                        {% for chat in mychats %}
                            <div class="chat" onclick="replace(`{{ chat.get_absolute_url }}`)">
                                <span class="title"><b>{{ chat.creator }}, </b>{{ chat.users }}</span>
                                <br>
                                <span>{{ chat.description }}</span>
                                <br>
                                <span>{{ chat.created }}</span>
                                <br>
                            </div>
                        {% endfor %}
                        {% for chat in otherchats %}
                            <div class="chat" onclick="replace(`{{ chat.get_absolute_url }}`)">
                                <span class="title"><b>{{ chat.creator }}, </b>{{ chat.users }}</span>
                                <br>
                                <span>{{ chat.description }}</span>
                                <br>
                                <span>{{ chat.created }}</span>
                                <br>
                            </div>
                        {% endfor %}
                </div> {% endcomment %}
            </div>
            <div class="chat-grid-space chat-grid-object">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/functions.js' %}" charset="utf-8" type="text/javascript"></script>
    <script src="{% static 'js/onLoad.js' %}" charset="utf-8" type="text/javascript"></script>
    <script src="{% static 'js/controls.js' %}" charset="utf-8" type="text/javascript"></script>
    {% block extrascripts %}
    {% endblock extrascripts %}
</body>
</html>