account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import SettingsView
from . import views

app_name = 'account'

urlpatterns = [
    path('auth/login/', auth_views.LoginView.as_view(), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('auth/signup/', views.main, name='signup'),

    path('auth/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('auth/password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('auth/password_reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('settings/', SettingsView.as_view(), name="settings_view"),
]

chat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home import views as home
from new_chat import views as new_chat
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(
        url=staticfiles_storage.url("media/favicon.jpg"))),
    path('', include('home.urls', namespace="home")),
    path('~/', include('client.urls', namespace='client')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('account/', include('account.urls', namespace="account")),
    path('newchat', new_chat.ChatCreateView.as_view(), name="new_chat"),
    path('apps/', include('management.urls', namespace="management")),

    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('rosetta/', include('rosetta.urls')),
    path("store/", include('store.urls', namespace="store")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from .views import AppListView

app_name = 'management'

urlpatterns = [
    path('', AppListView.as_view(), name='apps'),
]

store/urls.py
from django.urls import path

from store.views import AppListView

app_name = "store"

urlpatterns = [
    path('', AppListView.as_view(), name='list'),
]

management/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class AppGroup(models.Model):
    """Group Apps together."""

    name = models.CharField(max_length=50, verbose_name=_('name'))

    # 0 is the most important, 1 is very important, 2 is important, 3 is relevent, 4 is least important
    importance = models.PositiveIntegerField(
        verbose_name=_('importance'), default=4)

    class Meta:
        """Meta definition for AppGroup."""

        verbose_name = _('App Group')
        verbose_name_plural = _('App Groups')

    def __str__(self):
        """Unicode representation of AppGroup."""
        return self.name


class App(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("name"))
    url = models.CharField(_('URL'), max_length=50)
    logo = models.ImageField(_('Logo'), upload_to='app_images')

    # Cost per year
    cost_yearly = models.DecimalField(
        max_digits=5, decimal_places=2, default=0, verbose_name=_("cost yearly"))
    cost_monthely = models.DecimalField(
        max_digits=5, decimal_places=2, default=0, verbose_name=_("cost monthely"))
    group = models.ForeignKey(AppGroup, on_delete=models.CASCADE,
                              blank=True, null=True, default=None, verbose_name=_('group'))

    def get_cost(self):
        return "$" + str(self.cost)

    class Meta:
        verbose_name = _('App')
        verbose_name_plural = _('Apps')

    def __str__(self):
        return self.name

management/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import App

# Create your views here.


class AppListView(ListView, LoginRequiredMixin):
    model = App
    template_name_suffix = "_list"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(users=self.request.user.profile)

management/templates/management/app_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/app_list.css' %}">
{% endblock extrastyle %}
{% block content %}
    <div class="container">
        <input type="input"
               class="search"
               id="app_search"
               autocomplete="off"
               placeholder="Search..."
               autofocus>
        <div class="apps-container">
            {% for app in object_list %}
                <a class="app" href="{% url app.url %}">
                    <img src="{% thumbnail app.logo 70x70 %}" alt="Logo">
                    <p class='app-label'>{{ app.name }}</p>
                </a>
            {% empty %}
                <p class='no-apps'>
                    You don't have any apps, <a href="{% url 'store:list' %}">get one</a>.
                </p>
            {% endfor %}
        </div>
        <div class="extra-apps">
            <a class="settings-app app" href="{% url 'account:settings_view' %}">
                <img src="{% static 'images/settings-gear.png' %}"
                     width="110px"
                     height="70px"
                     alt="SettingsLogo">
                <p>Settings</p>
            </a>
        </div>
    </div>
{% endblock content %}
{% block extrascripts %}
    <script src="{% static 'js/app_list.js' %}"></script>
{% endblock extrascripts %}